"""Initial migration

Revision ID: 21f5f54a6c57
Revises: 
Create Date: 2025-03-24 02:42:34.324417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21f5f54a6c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS clients;")
    op.execute("CREATE SCHEMA IF NOT EXISTS users;")
    op.execute("CREATE SCHEMA IF NOT EXISTS risk;")
    op.execute("CREATE SCHEMA IF NOT EXISTS app;")

    op.execute("CREATE TABLE IF NOT EXISTS clients.clients_organizations (id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL, industry VARCHAR(64), description TEXT, website VARCHAR(128), created_at TIMESTAMP, updated_at TIMESTAMP);")
    print("Created clients_organizations")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS risk.cyber_threats (id SERIAL PRIMARY KEY, threat_type VARCHAR(32), title VARCHAR(128) NOT NULL, description TEXT, actor VARCHAR(64), tactics VARCHAR(256), techniques VARCHAR(256), affected_systems VARCHAR(256), indicators TEXT, risk_level VARCHAR(16), source VARCHAR(128), published_date DATE, created_at TIMESTAMP, updated_at TIMESTAMP);")
    print("Created cyber_threats")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS risk.geo_risks (id SERIAL PRIMARY KEY, country VARCHAR(64) NOT NULL, region VARCHAR(64), risk_type VARCHAR(32), title VARCHAR(128) NOT NULL, description TEXT, risk_level VARCHAR(16), source VARCHAR(128), published_date DATE, created_at TIMESTAMP, updated_at TIMESTAMP);")
    print("Created geo_risks")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS users.users_accounts (id SERIAL PRIMARY KEY, username VARCHAR(64) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(128) NOT NULL, first_name VARCHAR(64), last_name VARCHAR(64), is_active BOOLEAN, is_admin BOOLEAN, created_at TIMESTAMP, last_login TIMESTAMP);")
    print("Created users_accounts")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS clients.clients_contacts (id SERIAL PRIMARY KEY, client_id INTEGER NOT NULL, first_name VARCHAR(64) NOT NULL, last_name VARCHAR(64) NOT NULL, email VARCHAR(120), phone VARCHAR(20), position VARCHAR(64), notes TEXT, is_primary BOOLEAN, created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(client_id) REFERENCES clients.clients_organizations(id));")
    print("Created clients_contacts")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS clients.clients_locations (id SERIAL PRIMARY KEY, client_id INTEGER NOT NULL, name VARCHAR(128) NOT NULL, address VARCHAR(256), city VARCHAR(64), state VARCHAR(64), country VARCHAR(64), postal_code VARCHAR(20), location_type VARCHAR(32), created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(client_id) REFERENCES clients.clients_organizations(id));")
    print("Created clients_locations")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS risk.risk_assessments (id SERIAL PRIMARY KEY, client_id INTEGER NOT NULL, name VARCHAR(128) NOT NULL, assessment_date DATE NOT NULL, description TEXT, methodology VARCHAR(64), status VARCHAR(32), risk_score FLOAT, created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(client_id) REFERENCES clients.clients_organizations(id));")
    print("Created risk_assessments")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS clients.clients_assets (id SERIAL PRIMARY KEY, client_id INTEGER NOT NULL, name VARCHAR(128) NOT NULL, asset_type VARCHAR(32), description TEXT, importance VARCHAR(16), location_id INTEGER, technical_details TEXT, created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(client_id) REFERENCES clients.clients_organizations(id), FOREIGN KEY(location_id) REFERENCES clients.clients_locations(id));")
    print("Created clients_assets")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS risk.risk_recommendations (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL, title VARCHAR(128) NOT NULL, description TEXT, priority VARCHAR(16), implementation_cost VARCHAR(16), implementation_time VARCHAR(16), status VARCHAR(16), created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(assessment_id) REFERENCES risk.risk_assessments(id));")
    print("Created risk_recommendations")
    op.execute("COMMIT;")
    op.execute("CREATE TABLE IF NOT EXISTS risk.risk_findings (id SERIAL PRIMARY KEY, assessment_id INTEGER NOT NULL, title VARCHAR(128) NOT NULL, description TEXT, risk_level VARCHAR(16), impact TEXT, likelihood VARCHAR(16), asset_id INTEGER, evidence TEXT, created_at TIMESTAMP, updated_at TIMESTAMP, FOREIGN KEY(assessment_id) REFERENCES risk.risk_assessments(id), FOREIGN KEY(asset_id) REFERENCES clients.clients_assets(id));")
    print("Created risk_findings")
    op.execute("COMMIT;")

    # Existing table may not have all columns, add them
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS clients;")
    op.execute("DROP SCHEMA IF EXISTS users;")
    op.execute("DROP SCHEMA IF EXISTS risk;")
    op.execute("DROP SCHEMA IF EXISTS app;")

    op.create_table('apt_groups',
    sa.Column('apt_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sophistication_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_motivation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=20), server_default=sa.text("'enterprise'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint('sophistication_level >= 1 AND sophistication_level <= 5', name='apt_groups_sophistication_level_check'),
    sa.PrimaryKeyConstraint('apt_id', name='apt_groups_pkey')
    )

    op.drop_table('risk_findings')
    op.drop_table('risk_recommendations')
    op.drop_table('clients_assets')
    op.drop_table('risk_assessments')
    op.drop_table('clients_locations')
    op.drop_table('clients_contacts')
    op.drop_table('users_accounts')
    op.drop_table('geo_risks')
    op.drop_table('cyber_threats')
    op.drop_table('clients_organizations')
    op.execute("DROP SCHEMA IF EXISTS clients CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS users CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS risk CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE;")

    # ### end Alembic commands ###
