"""Initial migration

Revision ID: 21f5f54a6c57
Revises: 
Create Date: 2025-03-24 02:42:34.324417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21f5f54a6c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyber_threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('tactics', sa.String(length=256), nullable=True),
    sa.Column('techniques', sa.String(length=256), nullable=True),
    sa.Column('affected_systems', sa.String(length=256), nullable=True),
    sa.Column('indicators', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('risk_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_accounts_username'), ['username'], unique=True)

    op.create_table('clients_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('location_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('methodology', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_organizations.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['clients_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('implementation_cost', sa.String(length=16), nullable=True),
    sa.Column('implementation_time', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.String(length=16), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['clients_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apt_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_apt_groups_domain')

    op.drop_table('apt_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apt_groups',
    sa.Column('apt_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sophistication_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_motivation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=20), server_default=sa.text("'enterprise'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint('sophistication_level >= 1 AND sophistication_level <= 5', name='apt_groups_sophistication_level_check'),
    sa.PrimaryKeyConstraint('apt_id', name='apt_groups_pkey')
    )
    with op.batch_alter_table('apt_groups', schema=None) as batch_op:
        batch_op.create_index('idx_apt_groups_domain', ['domain'], unique=False)

    op.drop_table('risk_findings')
    op.drop_table('risk_recommendations')
    op.drop_table('clients_assets')
    op.drop_table('risk_assessments')
    op.drop_table('clients_locations')
    op.drop_table('clients_contacts')
    with op.batch_alter_table('users_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_users_accounts_email'))

    op.drop_table('users_accounts')
    op.drop_table('geo_risks')
    op.drop_table('cyber_threats')
    op.drop_table('clients_organizations')
    # ### end Alembic commands ###
