"""Add indexes for client search

Revision ID: 56dccf1bc6b0
Revises: 21f5f54a6c57
Create Date: 2025-03-26 01:05:45.538944

"""
from alembic import op
import sqlalchemy as sa
# Removed unused import: from sqlalchemy.dialects import postgresql
# Removed unused import: import geoalchemy2

# revision identifiers, used by Alembic.
revision = '56dccf1bc6b0'
down_revision = '21f5f54a6c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed redundant table creation calls

    # Add indexes for client search
    with op.batch_alter_table('clients_organizations', schema='clients') as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organizations_industry'), ['industry'], unique=False)

    with op.batch_alter_table('clients_locations', schema='clients') as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_locations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_locations_country'), ['country'], unique=False)

    # Keep other autogenerated changes if any (e.g., index on clients_assets.geo_location)
    # The autogenerate detected an index on geo_location, let's ensure it's kept if needed,
    # but it wasn't in the original plan. Assuming it was added manually or by another process.
    # If it was autogenerated based on the model, it should be fine.
    # Let's comment out the potentially problematic part if it causes issues.
    # with op.batch_alter_table('clients_assets', schema='clients') as batch_op:
    #     batch_op.create_index('idx_clients_assets_geo_location', ['geo_location'], unique=False, postgresql_using='gist')

    # Removed drop_table('apt_groups') as it seems unrelated or handled elsewhere
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed create_table('apt_groups')

    # Drop indexes for client search
    with op.batch_alter_table('clients_locations', schema='clients') as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_locations_country'))
        batch_op.drop_index(batch_op.f('ix_clients_locations_city'))

    with op.batch_alter_table('clients_organizations', schema='clients') as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organizations_industry'))
        batch_op.drop_index(batch_op.f('ix_clients_organizations_name'))

    # Drop other potentially autogenerated indexes if needed
    # with op.batch_alter_table('clients_assets', schema='clients') as batch_op:
    #     batch_op.drop_index('idx_clients_assets_geo_location', postgresql_using='gist')

    # Removed redundant table dropping calls
    # ### end Alembic commands ###
