"""Add public_profile_summary to Client model

Revision ID: f4b34866ee7a
Revises: a9cd93ec09ae
Create Date: 2025-03-28 01:56:44.694967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b34866ee7a'
down_revision = 'a9cd93ec09ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_profile_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_organizations', schema=None) as batch_op:
        batch_op.drop_column('public_profile_summary')

    # ### end Alembic commands ###
