"""Add competitors JSONB column to Client model

Revision ID: f9c67adde613
Revises: f4b34866ee7a
Create Date: 2025-03-28 03:14:20.604274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9c67adde613'
down_revision = 'f4b34866ee7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed erroneous create_table('users_accounts')
    with op.batch_alter_table('clients_organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients_organizations', schema=None) as batch_op:
        batch_op.drop_column('competitors')

    # Removed erroneous drop_table('users_accounts')
    # ### end Alembic commands ###
